config/routes.rb
Downloader::Application.routes.draw do
  resources :remote_files

end

app/models/remote_file.rb
class RemoteFile < ActiveRecord::Base

  require 'net/http'
  require 'uri'
  require 'UUID'
  include ActiveRecord::Transitions
  after_create :get_info
  belongs_to :site

  state_machine do
    state :added
    state :started
    state :finished
    state :paused
    state :stopped
    state :invalid

    event :start do
      transitions :to=>:started, :from => [:added, :paused], :guard => :start_download
    end
    event :finish do
      transitions :to => :finished, :from => :started
    end
    event :pause do
      transitions :to => :paused, :from => :started
    end
    event :stop do
      transitions :to => :stopped, :from => [:started, :paused]
    end
    event :invalidate do
      transitions :to => :invalid, :from => :added
    end
  end

  def start_download
    self.delay.download
  end

  def get_info

    url             = self.url

    url_base        = url.split('/')[2]
    url_path        = '/'+url.split('/')[3..-1].join('/')
    self.downloaded = 0
    begin

      Net::HTTP.start(url_base) do |http|
        headReq = Net::HTTP::Head.new(URI.escape(url_path))
        unless self.site.login.nil?
          headReq.basic_auth self.site.login, self.site.password
        end
        response           = http.request(headReq)
        self.original_name = URI.parse(url).path[%r{[^/]+\z}]
        self.name          = UUID.new.generate
        self.size          = response['content-length'].to_i
        self.save!
      end
    rescue Errno::ECONNREFUSED => e
      self.invalidate!
    end
  end

  def download
    url      = self.url

    url_base = url.split('/')[2]
    url_path = '/'+url.split('/')[3..-1].join('/')

    Net::HTTP.start(url_base) do |http|
      i =0
      File.open("public/downloads/"+self.name, 'w') { |f|
        getReq = Net::HTTP::Get.new(URI.escape(url_path))
        unless self.site.login.nil?
          getReq.basic_auth self.site.login, self.site.password
        end
        unless downloaded.nil?
          getReq.range = Range.new(downloaded, size)
        end
        http.request(getReq) do |res|
          if self.state == 'paused'
            self.save!
            return 0
          end
          res.read_body do |str|
            f.write str
            if self.state == "paused"
              self.save!
              return 0
            end
            self.downloaded += str.length
            if downloaded>i*(size/100)
              i += 1
              self.save!
              self.reload
            end
          end
        end

      }
    end
    unless downloaded != size
      self.finish!
    end
    self.save
  end

  def change_state=(new_state)
    if new_state == "Pause"
      self.pause!
    end
    if new_state == "Start"
      self.start!
    end
    if new_state == "Reset"
      FileUtils.rm('public/downloads/'+self.name)
      self.downloaded = 0
      self.save!
      self.start!
    end
  end

  def change_state
    return self.state
  end

end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :remote_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/remote_files_controller.rb
class RemoteFilesController < ApplicationController
  require 'uri'
  # GET /remote_files
  # GET /remote_files.xml
  def index
    @remote_files = RemoteFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @remote_files }
    end
  end

  # GET /remote_files/1
  # GET /remote_files/1.xml
  def show
    @remote_file = RemoteFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @remote_file }
    end
  end

  # GET /remote_files/new
  # GET /remote_files/new.xml
  def new
    @remote_file = RemoteFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @remote_file }
    end
  end

  # GET /remote_files/1/edit
  def edit
    @remote_file = RemoteFile.find(params[:id])
  end

  # POST /remote_files
  # POST /remote_files.xml
  def create
    @remote_file = RemoteFile.new(params[:remote_file])
    myUri = URI.parse( 'http://www.mglenn.com/directory' )
    s = Site.find_or_create_by_url(myUri.host)
    @remote_file.site=s




    respond_to do |format|
      if @remote_file.save
        unless @remote_file.invalid?
          @remote_file.start!
        end
        format.html { redirect_to(@remote_file, :notice => 'Remote file was successfully created.') }
        format.xml  { render :xml => @remote_file, :status => :created, :location => @remote_file }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @remote_file.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /remote_files/1
  # PUT /remote_files/1.xml
  def update
    @remote_file = RemoteFile.find(params[:id])
    if params[:redownload]
      @remote_file.delay.download
    end
    respond_to do |format|
      if @remote_file.update_attributes(params[:remote_file])
        format.html { redirect_to(@remote_file, :notice => 'Remote file was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @remote_file.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /remote_files/1
  # DELETE /remote_files/1.xml
  def destroy
    @remote_file = RemoteFile.find(params[:id])
    @remote_file.destroy

    respond_to do |format|
      format.html { redirect_to(remote_files_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/remote_files_helper.rb
module RemoteFilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Downloader</title>
  <%= stylesheet_link_tag :all %>

  <%= javascript_include_tag :all %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/remote_files/_form.html.erb
  <% semantic_form_for @remote_file do |form| %>

    <% form.inputs :name => "Basic" do %>
      <%= form.input :url , :cols => 30%>
      <%= form.input :change_state, :collection => ["Pause","Stop","Start"] %>
    <% end %>

      <% form.buttons do %>
      <%= form.commit_button %>
    <% end %>
  <% end %>

app/views/remote_files/_progressbar.html.erb
<div id="progressbar"></div>
<script>
	$(function() {
		$( "#progressbar" ).progressbar({
			value: <%= percentage*100 %>
		});
	});
    <% if @remote_file.started? %>
    updateValue();
        function updateValue(){
        $.ajax({
            type: "GET",
            url: "<%= remote_file_path(@remote_file) %>",
            dataType: "xml",
            success: function(xml) {
                var dled = parseInt($(xml).find('downloaded').text());
                var size = parseInt($(xml).find('size').text());
                $( "#progressbar" ).progressbar("value",((dled/size)*100));
                if((dled/size)<1)
                    setTimeout('updateValue();', 2000);
            }
        });


        }
  <% end %>

</script>

app/views/remote_files/edit.html.erb
<h1>Editing remote_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @remote_file %> |
<%= link_to 'Back', remote_files_path %>

app/views/remote_files/index.html.erb
<h1>Listing remote_files</h1>

<table>
  <tr>
    <th>Original name</th>
    <th>Site</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @remote_files.each do |remote_file| %>
  <tr>
    <td><%= remote_file.original_name %></td>
    <td><%= remote_file.site_id %></td>
    <td><%= remote_file.url %></td>
    <td><%= link_to 'Show', remote_file %></td>
    <td><%= link_to 'Edit', edit_remote_file_path(remote_file) %></td>
    <td><%= link_to 'Destroy', remote_file, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Remote file', new_remote_file_path %>

app/views/remote_files/new.html.erb
<h1>New remote_file</h1>

<%= render 'form' %>

<%= link_to 'Back', remote_files_path %>

app/views/remote_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Current File state:</b>
  <%= @remote_file.state %>
</p>

<p>
  <b>Original name:</b>
  <%= @remote_file.original_name %>
</p>

<p>
  <b>Site:</b>
  <%= @remote_file.site.url %>
</p>

<p>
  <b>Url:</b>
  <%= @remote_file.url %>
</p>

<p>
  <b>Size:</b>
  <%= @remote_file.size.to_f/1000000 %>
</p>

<%  if @remote_file.invalid? %>
<p>
  <b>This file is invalid</b>
</p>
    <% end %>

<% unless @remote_file.size.nil? %>
<p>
  <b>%:</b>
  <%= render :partial => 'progressbar', :locals =>{:percentage => (@remote_file.downloaded.to_f/@remote_file.size.to_f)} %>
</p>
    <% end %>
<%= link_to 'Edit', edit_remote_file_path(@remote_file) %> |
<%= link_to 'Back', remote_files_path %>